// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg4lRS1zJZohXvQtfIFk1ZRT788mwcY7o',
    appId: '1:908090659730:web:9ceed049ad10779e7ee74b',
    messagingSenderId: '908090659730',
    projectId: 'quiz-b9509',
    authDomain: 'quiz-b9509.firebaseapp.com',
    storageBucket: 'quiz-b9509.appspot.com',
    measurementId: 'G-XLB0QMKXVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDBLQ-KjmPrMt2NQPC0-DMK5iarrzFc8',
    appId: '1:908090659730:android:783e8af27f1093807ee74b',
    messagingSenderId: '908090659730',
    projectId: 'quiz-b9509',
    storageBucket: 'quiz-b9509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrhCGNoU4JTiqR4MNHTX-gcpVFtXVa39A',
    appId: '1:908090659730:ios:82e7f8b838e23cfc7ee74b',
    messagingSenderId: '908090659730',
    projectId: 'quiz-b9509',
    storageBucket: 'quiz-b9509.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrhCGNoU4JTiqR4MNHTX-gcpVFtXVa39A',
    appId: '1:908090659730:ios:2e3a4b86db8791407ee74b',
    messagingSenderId: '908090659730',
    projectId: 'quiz-b9509',
    storageBucket: 'quiz-b9509.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
